# <font color= blue>Découverte de Numpy</font>

## Introduction à Numpy

In [1]:
list_of_list = [["Paris", 75], ["Lyon", 69]]

Avantages des listes python:
* peuvent contenir différents types de données
* peuvent rétrécir et grandir dynamiquement

In [2]:
list = [1, "film", 3]

In [3]:
list.append("série")
print(list)

[1, 'film', 3, 'série']


Inconvénients des listes Python:
* consomment beaucoup d'énergie
* problématiques pour des datasets de moyenne à très grande taille

## Les tableaux avec Numpy

ndarray

In [4]:
import numpy as np

In [5]:
vector = np.array([3, 4, 17, 65])

In [6]:
print(vector)

[ 3  4 17 65]


In [7]:
matrix = np.array([[2, 5, 15], [20, 50, 30], [34, 99, 45]])

In [8]:
print(matrix)

[[ 2  5 15]
 [20 50 30]
 [34 99 45]]


In [9]:
# vector est un tableau contenant une unique colonne
# matrix est un tableau contenant des lignes et des colonnes

## Exo

* Créer un vecteur depuis la liste [10, 20, 30]
    * Assigner le résultat à la variable vector

* Créer une matrice depuis la liste de listes suivante : [[5, 10, 15], [20, 25, 30], [35, 40, 45]]
    * Assigner le résultat à la variable matrix

In [10]:
vector = np.array([10, 20, 30])
print(vector)

[10 20 30]


In [11]:
matrix = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
print(matrix)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [ ]:
np.array()

In [12]:
vecteur= [0,1,2,3,4]

In [14]:
type(vecteur)

list

In [16]:
vectorr = np.array(vecteur)

In [17]:
type(vectorr)

numpy.ndarray

## Taille d'un tableau

ndarray.shape

shape retournera un tuple avec un élément, un tuple étant une liste où aucun élément ne peut être modifié

In [5]:
import numpy as np

tablo_exo = np.array(['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'])
print(tablo_exo)

['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']


In [7]:
tablo_deux = np.array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'], ['1986', 'Americas', 'Uruguay', 'Other', '0.5'], ['1985', 'Africa', 'Cote d/Ivoire', 'Wine', '1.62']])
print(tablo_deux)

[['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Africa' 'Cote d/Ivoire' 'Wine' '1.62']]


In [8]:
vector = np.array([1, 2, 3, 4])
print(vector.shape)

(4,)


In [10]:
print(tablo_exo.shape)

(5,)


In [11]:
print(tablo_deux.shape)

(3, 5)


In [12]:
vector = np.array([10, 20, 30])
print(vector)

matrix = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
print(matrix)

[10 20 30]
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [15]:
vector_shape = vector.shape
matrix_shape = matrix.shape

print(vector_shape)

print(matrix_shape)

(3,)
(3, 3)


vector possède trois colonnes et matrix trois colonnes et trois lignes

## Lire un dataset avec Numpy

In [17]:
# Fonction numpy pour lire un dataset: numpy.genfromtxt()

In [18]:
# exemple : 
# import numpy as np
# test = np.genfromtxt("data.csv", delimiter= ",")


# le code va lire le fichier data.csv dans un tableau numpy et l'enregistrer
#dans la variable "test"

Exo :

* Utiliser la fonction numpy.genfromtxt() pour lire le fichier "world_alcohol.csv" dans un tableau qu'on nommera world_alcohol

* Utiliser les fonctions type() et print() pour afficher le type de world_alcohol

In [23]:
import numpy as np
world_alcohol = np.genfromtxt("world_alcohol.csv", delimiter= ",")

In [24]:
print(world_alcohol)

[[      nan       nan       nan       nan       nan]
 [1.986e+03       nan       nan       nan 0.000e+00]
 [1.986e+03       nan       nan       nan 5.000e-01]
 ...
 [1.986e+03       nan       nan       nan 2.540e+00]
 [1.987e+03       nan       nan       nan 0.000e+00]
 [1.986e+03       nan       nan       nan 5.150e+00]]


In [25]:
type(world_alcohol)

numpy.ndarray

In [26]:
print(type(world_alcohol))

<class 'numpy.ndarray'>


## Les types de données avec Numpy

In [35]:
# bool --> True ou False
# int --> integer (les entiers) et dans ce type de donnée on aura :
#        int16
#        int32
#        int64
#Ils indiquent le nombre de BIT

# float --> nombres décimales
# string --> chaîne de caractère

In [36]:
# La particularité d'un tableau numpy :
# Toutes les valeurs de différentes colonnes sont de même types de données.
# Numpy détermine automatiquement le type de donnée adapté à la situation
#lorsqu'il lit le dataset et qu'il le convertit en tableau

In [37]:
# Pour déterminer le type de donnée d'un tableau avec la fonction : dtype

In [41]:
numbers = np.array([1, 2, 3, 4])

In [42]:
numbers.dtype

dtype('int32')

* Assigner le type de données de world_alcohol à la variable world_alcohol_dtype

* Afficher world_alcohol_dtype

In [43]:
world_alcohol_dtype = world_alcohol.dtype

In [44]:
print(world_alcohol_dtype)

float64


## Afficher les données correctement

In [4]:
import numpy as np
world_alcohol = np.genfromtxt("world_alcohol.csv", delimiter=",", dtype="U75", skip_header=1)
world_alcohol

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ...,
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

## Extraire une valeur depuis un tableau Numpy

In [6]:
vector = np.array([5,10,15,20])
print(vector[0])

5


In [7]:
list_of_lists = [[5,10,15], [20,25,30]]

In [13]:
first_row = list_of_lists[0]
# extraire la première liste en demandant l'indice 0

In [14]:
first_row[2]
# Extraire l'élément '15' de la première liste

15

In [15]:
#condenser l'écriture

list_of_lists[0][2]

15

In [16]:
matrix = np.array([[5,10,15], [20,25,30]])

In [17]:
#essayer de récupérer l'élément '30'

In [18]:
matrix[1,2]

30

In [20]:
# ligne d'indice 1 position 2
#et colonne d'indice 2 soit position 3

### Exo

* Assigner le nombre de litres de vin bu par un Ivoirien en 1985 à la variable ivoire_1985.
Cela correspond à la donnée de la 3e ligne.
* Assigner le nom du pays de la 2e ligne à la variable second_country.

In [22]:
import numpy as np
world_alcohol = np.genfromtxt("world_alcohol.csv", delimiter=",", dtype="U75", skip_header=1)
world_alcohol

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ...,
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

In [25]:
ivoire_1985 = world_alcohol[2,4]
ivoire_1985

'1.62'

In [26]:
second_country = world_alcohol[1,2]
second_country

'Uruguay'

In [27]:
print(ivoire_1985)
print(second_country)

1.62
Uruguay


## Extraire un vecteur de valeurs depuis un tableau Numpy

In [28]:
vector = np.array([5,10,15,20])

In [29]:
vector[0:3]

array([ 5, 10, 15])

In [30]:
# On a extrait un vector avec les trois premières valeurs du vecteur initiale
# ça commence par l'indice 0 (ici c'est 5) et ça ne prend pas la valeur après l'indice 3

In [31]:
matrix = np.array([[5,10,15], [20,25,30], [35,40,45]])

In [32]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [37]:
matrix[:,1]
#premier élément avant la virgule joue sur les lignes
#deuxième élément après la virgule joue sur les colonnes
# ':' signifie qu'on sélectionne toutes les lignes
# on vient de lui demander de retourner toute la ligne de la seconde colonne (indice 1)

array([10, 25, 40])

In [38]:
matrix[2,:]

array([35, 40, 45])

In [39]:
#cette fois-ci on obtient la troisième ligne qui correspond à l'indice 2
#et on lui demande les données de toutes les colonnes

In [45]:
matrix[1:3,1]

array([25, 40])

In [46]:
#On vise la colonne du milieu avec l'indice 1
#pour les lignes (1:3), on lui demande la donnée en indice 1 (25) jusqu'à '40' (indice 3 exclu)

## Exo

* Assigner toute la 3e colonne de world_alcohol à la variable countries.
* Assigner l'ensemble de la 5e colonne de world_alcohol à la variable alcohol_consumption.

In [51]:
import numpy as np
world_alcohol = np.genfromtxt("world_alcohol.csv", delimiter=",", dtype="U75", skip_header=1)
world_alcohol

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ...,
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

In [52]:
countries = world_alcohol[:,2]
print(countries)

['Viet Nam' 'Uruguay' "Cte d'Ivoire" ... 'Switzerland' 'Papua New Guinea'
 'Swaziland']


In [53]:
alcohol_consumption = world_alcohol[:,4]
print(alcohol_consumption)

['0' '0.5' '1.62' ... '2.54' '0' '5.15']


## Extraire un tableau de valeurs depuis un tableau Numpy

In [54]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [55]:
matrix[:,0:2]

array([[ 5, 10],
       [20, 25],
       [35, 40]])

In [56]:
#On a sélectionné toutes les lignes à l'aide du ':'
#et on affiche seulement les deux premières colonnes avec l'indice 0 à 2 (troisième colonnes exclue)

In [57]:
matrix[1:3,:]

array([[20, 25, 30],
       [35, 40, 45]])

In [58]:
#ça retourne un tableau qui correspond à toutes les colonnes mais seulement la ligne 2 et 3 (indices 1 3)

In [59]:
matrix[1:3,0:2]

array([[20, 25],
       [35, 40]])

In [61]:
#matrix deux lignes et deux colonnes
#on extrait les deux premières colonnes et les deux dernières lignes

## Exo

* Assigner toutes les lignes des 2 premières colonnes de world_alcohol à la variable first_two_columns.
* Assigner les 10 premières lignes de la première colonne de world_alcohol à la variable first_ten_years.
* Assigner les 10 premières lignes de toutes les colonnes de world_alcohol à la variable first_ten_rows.
* Assigner les 20 premières lignes des colonnes d'indice 1 et 2 de world_alcohol à la variable first_twenty_regions.

In [62]:
import numpy as np
world_alcohol = np.genfromtxt("world_alcohol.csv", delimiter=",", dtype="U75", skip_header=1)
world_alcohol

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ...,
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

In [64]:
first_two_columns = world_alcohol[:,0:2]
print(first_two_columns)

[['1986' 'Western Pacific']
 ['1986' 'Americas']
 ['1985' 'Africa']
 ...
 ['1986' 'Europe']
 ['1987' 'Western Pacific']
 ['1986' 'Africa']]


In [68]:
first_ten_years = world_alcohol[0:10,0]
print(first_ten_years)

['1986' '1986' '1985' '1986' '1987' '1987' '1987' '1985' '1986' '1984']


In [69]:
first_ten_rows = world_alcohol[0:10,:]
print(first_ten_rows)

[['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Africa' "Cte d'Ivoire" 'Wine' '1.62']
 ['1986' 'Americas' 'Colombia' 'Beer' '4.27']
 ['1987' 'Americas' 'Saint Kitts and Nevis' 'Beer' '1.98']
 ['1987' 'Americas' 'Guatemala' 'Other' '0']
 ['1987' 'Africa' 'Mauritius' 'Wine' '0.13']
 ['1985' 'Africa' 'Angola' 'Spirits' '0.39']
 ['1986' 'Americas' 'Antigua and Barbuda' 'Spirits' '1.55']
 ['1984' 'Africa' 'Nigeria' 'Other' '6.1']]


In [71]:
first_twenty_regions = world_alcohol[0:20,1:3]
print(first_twenty_regions)

[['Western Pacific' 'Viet Nam']
 ['Americas' 'Uruguay']
 ['Africa' "Cte d'Ivoire"]
 ['Americas' 'Colombia']
 ['Americas' 'Saint Kitts and Nevis']
 ['Americas' 'Guatemala']
 ['Africa' 'Mauritius']
 ['Africa' 'Angola']
 ['Americas' 'Antigua and Barbuda']
 ['Africa' 'Nigeria']
 ['Africa' 'Botswana']
 ['Americas' 'Guatemala']
 ['Western Pacific' "Lao People's Democratic Republic"]
 ['Eastern Mediterranean' 'Afghanistan']
 ['Western Pacific' 'Viet Nam']
 ['Africa' 'Guinea-Bissau']
 ['Americas' 'Costa Rica']
 ['Africa' 'Seychelles']
 ['Europe' 'Norway']
 ['Africa' 'Kenya']]


# <font color=blue> Analyse de données avec Numpy </font>

In [53]:
import numpy as np
world_alcohol = np.genfromtxt("world_alcohol.csv", delimiter=",", dtype="U75", skip_header=1)
world_alcohol

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ...,
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

## Effectuer des comparaisons

In [3]:
vector= np.array([5,10,15,20])

In [10]:
vector == 10

array([False,  True, False, False])

In [13]:
matrix = np.array ([[5,10,15],[20,25,30],[35,40,45]])
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [12]:
matrix == 25

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

Exo

* Extraire la 3e colonne de world_alcohol et comparer la au pays "Canada". Assigner le résultat à la variable countries_canada.
* Extraire la première colonne de world_alcohol et comparer la à la chaîne de caractères "1984". Assigner le résultat à la variable years_1984.

In [14]:
import numpy as np
world_alcohol = np.genfromtxt("world_alcohol.csv", delimiter=",", dtype="U75", skip_header=1)
world_alcohol

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ...,
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

In [31]:
countries_canada = world_alcohol[:,2]
print(countries_canada)
countries_canada == "Canada"

#écriture condensé :
#countries_canada = (world_alcohol[:,2] == "Canada")

['Viet Nam' 'Uruguay' "Cte d'Ivoire" ... 'Switzerland' 'Papua New Guinea'
 'Swaziland']


array([False, False, False, ..., False, False, False])

In [32]:
years_1984 = world_alcohol[:,0]
print(years_1984)
years_1984 == "1984"

['1986' '1986' '1985' ... '1986' '1987' '1986']


array([False, False, False, ..., False, False, False])

## Sélectionner des éléments

In [33]:
vector = np.array([5,10,15,20])
equal_to_ten = (vector == 10)
print(vector[equal_to_ten])

[10]


In [34]:
#nous avons créé un vector puis
#le code va comparer chaque valeur de la variable vector à la variable 10.
#equal_to_ten va afficher le seul résultat qui est Vrai

In [35]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [70]:
second_column_25 = (matrix[:,1] == 25)
print(matrix[second_column_25, :])

[[20 25 30]]


In [37]:
#il affiche la ligne contenant la valeur 25.

Exo

* Comparer la 3e colonne de world_alcohol à la chaine de caractères "Algeria".
* Assigner le résultat à la variable country_is_algeria.
* Sélectionner seulement les lignes de world_alcohol pour lesquelles country_is_algeria vaut True.
* Assigner le résultat à la variable country_algeria.
* Afficher les résultats.
* Faire le même travail pour récupérer toutes les lignes correcpondantes à l'année "1984". Assigner le résultat à la variable years_1984.

In [76]:
import numpy as np
world_alcohol = np.genfromtxt("world_alcohol.csv", delimiter=",", dtype="U75", skip_header=1)
world_alcohol

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ...,
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

In [73]:
country_is_algeria = (world_alcohol[:, 2] == "Algeria")
country_algeria = world_alcohol[country_is_algeria]
print(country_algeria)

[['1984' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1987' 'Africa' 'Algeria' 'Beer' '0.17']
 ['1987' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1986' 'Africa' 'Algeria' 'Wine' '0.1']
 ['1984' 'Africa' 'Algeria' 'Other' '0']
 ['1989' 'Africa' 'Algeria' 'Beer' '0.16']
 ['1989' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1989' 'Africa' 'Algeria' 'Wine' '0.23']
 ['1986' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1984' 'Africa' 'Algeria' 'Wine' '0.12']
 ['1985' 'Africa' 'Algeria' 'Beer' '0.19']
 ['1985' 'Africa' 'Algeria' 'Other' '0']
 ['1986' 'Africa' 'Algeria' 'Beer' '0.18']
 ['1985' 'Africa' 'Algeria' 'Wine' '0.11']
 ['1986' 'Africa' 'Algeria' 'Other' '0']
 ['1989' 'Africa' 'Algeria' 'Other' '0']
 ['1987' 'Africa' 'Algeria' 'Other' '0']
 ['1984' 'Africa' 'Algeria' 'Beer' '0.2']
 ['1985' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1987' 'Africa' 'Algeria' 'Wine' '0.1']]


In [47]:
year_is_1984 = world_alcohol[:,0] == "1984"
years_1984 = world_alcohol[year_is_1984]
print(years_1984)

[['1984' 'Africa' 'Nigeria' 'Other' '6.1']
 ['1984' 'Eastern Mediterranean' 'Afghanistan' 'Other' '0']
 ['1984' 'Americas' 'Costa Rica' 'Wine' '0.06']
 ...
 ['1984' 'Europe' 'Latvia' 'Spirits' '7.5']
 ['1984' 'Africa' 'Angola' 'Wine' '0.57']
 ['1984' 'Africa' 'Central African Republic' 'Wine' '0.46']]


In [48]:
years_1984 = world_alcohol[world_alcohol[:,0] == "1984"]
print(years_1984)

[['1984' 'Africa' 'Nigeria' 'Other' '6.1']
 ['1984' 'Eastern Mediterranean' 'Afghanistan' 'Other' '0']
 ['1984' 'Americas' 'Costa Rica' 'Wine' '0.06']
 ...
 ['1984' 'Europe' 'Latvia' 'Spirits' '7.5']
 ['1984' 'Africa' 'Angola' 'Wine' '0.57']
 ['1984' 'Africa' 'Central African Republic' 'Wine' '0.46']]


## Effectuer des comparaisons avec plusieurs conditions

In [1]:
# pour réaliser des conditions multiples, on utilise les opérateurs "and" ou "or" 

In [7]:
import numpy as np
vector = np.array([5,10,15,20])
vector

array([ 5, 10, 15, 20])

In [8]:
equal_to_ten_and_five = (vector == 10) & (vector == 5)
print(equal_to_ten_and_five)

[False False False False]


In [9]:
equal_to_ten_or_five = (vector == 10) | (vector == 5)
print(equal_to_ten_or_five)

[ True  True False False]


Exo

* Sélectionner les lignes dont le pays est "Algeria" et l'année "1986".

* Créer cette double comparaison et assigner le résultat à la variable is_algeria_and_1986.
* Utiliser is_algeria_and_1986 pour sélectionner les lignes correspondantes dans le tableau world_alcohol.
* Assigner le résultat à la variable rows_with_algeria_and_1986.
* Afficher le résultat.

In [10]:
import numpy as np
world_alcohol = np.genfromtxt("world_alcohol.csv", delimiter=",", dtype="U75", skip_header=1)
world_alcohol

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ...,
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

In [17]:
country_is_algeria = (world_alcohol[:, 2] == "Algeria")
country_algeria = world_alcohol[country_is_algeria]
print(country_algeria)
print(country_algeria.shape)

[['1984' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1987' 'Africa' 'Algeria' 'Beer' '0.17']
 ['1987' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1986' 'Africa' 'Algeria' 'Wine' '0.1']
 ['1984' 'Africa' 'Algeria' 'Other' '0']
 ['1989' 'Africa' 'Algeria' 'Beer' '0.16']
 ['1989' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1989' 'Africa' 'Algeria' 'Wine' '0.23']
 ['1986' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1984' 'Africa' 'Algeria' 'Wine' '0.12']
 ['1985' 'Africa' 'Algeria' 'Beer' '0.19']
 ['1985' 'Africa' 'Algeria' 'Other' '0']
 ['1986' 'Africa' 'Algeria' 'Beer' '0.18']
 ['1985' 'Africa' 'Algeria' 'Wine' '0.11']
 ['1986' 'Africa' 'Algeria' 'Other' '0']
 ['1989' 'Africa' 'Algeria' 'Other' '0']
 ['1987' 'Africa' 'Algeria' 'Other' '0']
 ['1984' 'Africa' 'Algeria' 'Beer' '0.2']
 ['1985' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1987' 'Africa' 'Algeria' 'Wine' '0.1']]
(20, 5)


In [18]:
years_1986 = world_alcohol[world_alcohol[:, 0] == "1986"]
print(years_1986)
print(years_1986.shape)

[['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1986' 'Americas' 'Colombia' 'Beer' '4.27']
 ...
 ['1986' 'Western Pacific' 'Fiji' 'Spirits' '0.05']
 ['1986' 'Europe' 'Switzerland' 'Spirits' '2.54']
 ['1986' 'Africa' 'Swaziland' 'Other' '5.15']]
(651, 5)


In [33]:
#Faux car les deux éléments de condtion on des tailles différentes. 
is_algeria_and_1986 = (country_algeria == "Algeria") & (years_1986 == "1986")

ValueError: operands could not be broadcast together with shapes (20,5) (651,5) 

In [40]:
#On combine les deux conditions en les fixant avec le signe &. 
#Il faut bien pensé à appliquer la condition sur un même élément afin que numpy
#Soit en mesure de fonctionner
#On isole les conditions avec des () et on les applique à un tableau numpy grace aux [] qui peuvent contenir 
#Les tableaux booleen générés par la condition et les appliquer sur notre tableau. 
is_algeria_and_1986 = world_alcohol[(world_alcohol[:,2] == "Algeria") & (world_alcohol[:, 0] == "1986")]
is_algeria_and_1986

array([['1986', 'Africa', 'Algeria', 'Wine', '0.1'],
       ['1986', 'Africa', 'Algeria', 'Spirits', '0.01'],
       ['1986', 'Africa', 'Algeria', 'Beer', '0.18'],
       ['1986', 'Africa', 'Algeria', 'Other', '0']], dtype='<U75')

On voit bien ci-dessous que les tailles visées par la condition sont similaires. 

In [24]:
world_alcohol[:,2].shape

(3257,)

In [25]:
world_alcohol[:, 0].shape

(3257,)

On peut décomposer l'opération en deux conditions appliquées l'une après l'autre de manière successive. 
<ul><li>On Filtre tous les résultats de l'année 1986</li>
<li>Puis on applique sur le tableau obtenue le filtre sur les pays pour ne garder que les résultats : Algérie</li></ul>

In [35]:
year_test = years_1986[years_1986[:,2] == "Algeria"]

In [36]:
year_test

array([['1986', 'Africa', 'Algeria', 'Wine', '0.1'],
       ['1986', 'Africa', 'Algeria', 'Spirits', '0.01'],
       ['1986', 'Africa', 'Algeria', 'Beer', '0.18'],
       ['1986', 'Africa', 'Algeria', 'Other', '0']], dtype='<U75')

In [37]:
alge_1986

array([['1986', 'Africa', 'Algeria', 'Wine', '0.1'],
       ['1986', 'Africa', 'Algeria', 'Spirits', '0.01'],
       ['1986', 'Africa', 'Algeria', 'Beer', '0.18'],
       ['1986', 'Africa', 'Algeria', 'Other', '0']], dtype='<U75')

In [39]:
rows_with_algeria_and_1986 = world_alcohol[(world_alcohol[:,2] == "Algeria") & (world_alcohol[:, 0] == "1986")]
rows_with_algeria_and_1986

array([['1986', 'Africa', 'Algeria', 'Wine', '0.1'],
       ['1986', 'Africa', 'Algeria', 'Spirits', '0.01'],
       ['1986', 'Africa', 'Algeria', 'Beer', '0.18'],
       ['1986', 'Africa', 'Algeria', 'Other', '0']], dtype='<U75')

## Remplacer des valeurs dans un tableau Numpy

In [41]:
vector

array([ 5, 10, 15, 20])

In [42]:
equal_to_ten_or_five = (vector == 10) | (vector == 5)
print(equal_to_ten_or_five)

[ True  True False False]


In [43]:
vector[equal_to_ten_or_five] = 50
print(vector)

[50 50 15 20]


In [44]:
#On est partie d'un vecteur existant, on a comparé ce vecteur avec ses valeurs 10 et 5
#et on a sélectionné ensuite les éléments des vecteurs pour lesquels equal_to_ten_or_five est égal à True
#enfin on a rajouté "= 50" pour remplacer les valeurs sélectionnées par la valeur 50.

In [52]:
#On peut faire la même chose avec une matrice mais il faut bien se placer
#sur une même ligne ou une même colonne

matrix = np.array ([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [53]:
second_colunm_25 = matrix[:,1] == 25
print(second_colunm_25)

[False  True False]


In [54]:
matrix[second_colunm_25, 1] = 10
print(matrix)

[[ 5 10 15]
 [20 10 30]
 [35 40 45]]


Exo

* Créer un tableau numpy world_alcohol_2 égal world_alcohol pour le dupliquer sous un autre nom.

In [77]:
world_alcohol_2 = world_alcohol.copy()

In [79]:
world_alcohol_2

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ...,
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

* Remplacer toutes les années "1986" de la première colonne de world_alcohol_2 par "2018".
* Remplacer tous les alcools "Wine" de la 4e colonne de world_alcohol_2 par "Beer".

In [80]:
year_2018 = world_alcohol_2[:,0] == "1986"
print(year_2018)

[ True  True False ...  True False  True]


In [81]:
world_alcohol_2[year_2018, 0] = "2018"
print(world_alcohol_2)

[['2018' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['2018' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Africa' "Cte d'Ivoire" 'Wine' '1.62']
 ...
 ['2018' 'Europe' 'Switzerland' 'Spirits' '2.54']
 ['1987' 'Western Pacific' 'Papua New Guinea' 'Other' '0']
 ['2018' 'Africa' 'Swaziland' 'Other' '5.15']]


In [82]:
alcohol_beer = world_alcohol_2[:, 3] == "Wine"
print(alcohol_beer)

[ True False  True ... False False False]


In [83]:
world_alcohol_2[alcohol_beer, 3] = "Beer"
world_alcohol_2

array([['2018', 'Western Pacific', 'Viet Nam', 'Beer', '0'],
       ['2018', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Beer', '1.62'],
       ...,
       ['2018', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['2018', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

## Remplacer les chaines de caractères vides

* Comparer tous les éléments de la 5e colonne de world_alcohol avec la chaine de caractères vides c'est à dire ".
* Assigner le résultat à la variable is_value_empty.
* Sélectionner toutes les valeurs de la 5e colonne de world_alcohol pour lesquelles is_value_empty est égal à True et enfin les remplacer par la chaine de caractère '0'.

In [5]:
import numpy as np
world_alcohol = np.genfromtxt("world_alcohol.csv", delimiter=",", dtype="U75", skip_header=1)
world_alcohol

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ...,
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

In [7]:
is_value_empty = world_alcohol[: , 4] == ''
is_value_empty

array([False, False, False, ..., False, False, False])

In [14]:
world_alcohol[is_value_empty, 4] = '0'
print(world_alcohol)

[['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Africa' "Cte d'Ivoire" 'Wine' '1.62']
 ...
 ['1986' 'Europe' 'Switzerland' 'Spirits' '2.54']
 ['1987' 'Western Pacific' 'Papua New Guinea' 'Other' '0']
 ['1986' 'Africa' 'Swaziland' 'Other' '5.15']]


## Convertir des types de données

astype()

In [15]:
vector = np.array (["1", "2", "3"])

In [16]:
vector = vector.astype(float)

In [17]:
vector

array([1., 2., 3.])

* Extraire la 5e colonne de world_alcohol et assigner le résultat à la variable alcohol_consumption.
* Utiliser la méthode astype() pour convertir alcohol_consumption en décimal (float).

In [18]:
world_alcohol

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ...,
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

In [22]:
alcohol_consumption = world_alcohol[: , 4]
print(alcohol_consumption)

['0' '0.5' '1.62' ... '2.54' '0' '5.15']


In [24]:
alcohol_consumption = alcohol_consumption.astype(float)
print(alcohol_consumption)

[0.   0.5  1.62 ... 2.54 0.   5.15]


## Réaliser des calculs mathémathiques avec Numpy

sum() calcule la somme de tous les éléments d'un vecteur ou sur une dimension d'une matrice.

mean() calcule la moyenne de tous les éléments d'un vecteur ou la moyenne d'une dimension d'une matrice.

max() identifie la valeur maximale parmi les valeurs d'un vecteur ou le maximum sur une dimension d'une matrice.

Dimension d'une matrice : Soit on se place sur les lignes, soit on se place sur les colonnes.

In [25]:
vector = np.array([5, 10, 15, 20])

In [26]:
vector.sum()

50

In [31]:
#la somme de tous les éléments

In [32]:
vector.mean()

12.5

In [33]:
#la somme divisée par les 4 éléments

In [34]:
vector.max()

20

In [35]:
#montre la plus grande valeur

Avec une matrice, il faut spécifier un autre paramètre c'est l'argument <b>axis</b>, qui précise sur quelle dimension on réalise l'opération.
* <b>1</b> signifie qu'on réalise le calcule sur chaque <b>ligne</b>.
* <b>0</b> signifie qu'on réalise le calcule sur chaque <b>colonne</b>.

In [36]:
matrix = np.array([[5,10,15], [20,25,30], [35,40,45]])

In [37]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [38]:
#on va faire la somme sur les lignes

In [39]:
matrix.sum(axis=1)

array([ 30,  75, 120])

In [40]:
matrix.sum(axis=0)

array([60, 75, 90])

* Utiliser la méthode sum() pour calculer la somme des valeurs de alcohol_consumption. Assigner le résultat à la variable total_alcohol.
* Utiliser la méthode mean() pour calculer la moyenne des valeurs de alcohol_consumption. Assigner le résultat à la variable average_alcohol.
* Afficher les résultats.

In [41]:
alcohol_consumption

array([0.  , 0.5 , 1.62, ..., 2.54, 0.  , 5.15])

In [42]:
total_alcohol = alcohol_consumption.sum()

In [43]:
average_alcohol = alcohol_consumption.mean()

In [44]:
total_alcohol

3908.96

In [45]:
average_alcohol

1.2001719373656738

## Calculer la consommation totale annuelle par habitant pour un pays donné

In [131]:
import numpy as np
world_alcohol = np.genfromtxt("world_alcohol.csv", delimiter=",", dtype="U75", skip_header=1)
world_alcohol

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ...,
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

In [132]:
print(world_alcohol[world_alcohol[:, 2] == "Canada"])

[['1984' 'Americas' 'Canada' 'Spirits' '3.35']
 ['1989' 'Americas' 'Canada' 'Wine' '1.27']
 ['1984' 'Americas' 'Canada' 'Beer' '5']
 ['1985' 'Americas' 'Canada' 'Beer' '4.94']
 ['1987' 'Americas' 'Canada' 'Wine' '1.3']
 ['1987' 'Americas' 'Canada' 'Beer' '4.83']
 ['1986' 'Americas' 'Canada' 'Other' '']
 ['1986' 'Americas' 'Canada' 'Spirits' '3.11']
 ['1985' 'Americas' 'Canada' 'Spirits' '3.21']
 ['1985' 'Americas' 'Canada' 'Other' '']
 ['1986' 'Americas' 'Canada' 'Beer' '4.87']
 ['1984' 'Americas' 'Canada' 'Wine' '1.24']
 ['1989' 'Americas' 'Canada' 'Spirits' '2.91']
 ['1984' 'Americas' 'Canada' 'Other' '']
 ['1985' 'Americas' 'Canada' 'Wine' '1.29']
 ['1987' 'Americas' 'Canada' 'Spirits' '2.99']
 ['1989' 'Americas' 'Canada' 'Beer' '4.82']
 ['1989' 'Americas' 'Canada' 'Other' '']
 ['1986' 'Americas' 'Canada' 'Wine' '1.33']
 ['1987' 'Americas' 'Canada' 'Other' '']]


* Créer une matrice qu'on nommera canada_1986 qui contient toutes les lignes de world-alcohol correspondant à l'année "1986" et au pays "Canada".
* Extraire la 5e colonne de canada_1986, remplacer tout chaine de caractères vides (") par '0' et convertir la colonne en décimal (float). Assigner le résultat à la variable canada_alcohol.
* Calculer la somme de canada_ alcohol. Assigner le résultat à la variable total_canadian_drinking.
* Afficher le résultat.

In [133]:
canada_1986 = world_alcohol[(world_alcohol[:, 0] == "1986") & (world_alcohol[:, 2] == "Canada")]
canada_1986

array([['1986', 'Americas', 'Canada', 'Other', ''],
       ['1986', 'Americas', 'Canada', 'Spirits', '3.11'],
       ['1986', 'Americas', 'Canada', 'Beer', '4.87'],
       ['1986', 'Americas', 'Canada', 'Wine', '1.33']], dtype='<U75')

In [134]:
canada_alcohol = canada_1986[: , 4]

In [135]:
canada_alcohol

array(['', '3.11', '4.87', '1.33'], dtype='<U75')

In [139]:
empty_string = canada_alcohol == ''
canada_alcohol[empty_string] = "0"
print(canada_alcohol)

['0' '3.11' '4.87' '1.33']


In [140]:
canada_alcohol= canada_alcohol.astype(float)
canada_alcohol

array([0.  , 3.11, 4.87, 1.33])

In [141]:
total_canadian_drinking = canada_alcohol.sum()
total_canadian_drinking

9.31

## Calculer la consommation pour chaque pays

In [3]:
import numpy as np
world_alcohol = np.genfromtxt("world_alcohol.csv", delimiter=",", dtype="U75", skip_header=1)
world_alcohol

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ...,
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

* Tout d'abord, on crée un dictionnaire vide qui va contenir tous les pays et leurs consonmmations d'alcool associées, on le nommera totals.
* Sélectionner ensuite les lignes de world_alcohol correspondant à l'année donnée, disons 1989. Assigner le résultat à la variable year.
* Sélectionner dans une liste qu'on nommera countrie tous les pays.
* Parcourir tous les pays de la liste à l'aide d'une boucle. Pour chaque pays :
    * Sélectionner les lignes de year correspondant à ce pays.
    * Assigner le résultat à la variable country_consumption
    * Extraire la 5e colonne de country_consumption
    * Remplacer toute chaine de caractère vide dans cette colonne par 0
    * Convertir la colonne en décimal (float)
    * Calculer la somme de la colonne
    * Ajouter la somme au dictionnaire totals, avec comme clé le nom du pays et en valeur cette somme.
* Afficher le dictionnaire totals.

In [4]:
totals = {}

In [5]:
is_year = world_alcohol[:, 0] == "1989"
year = world_alcohol[is_year, :]
year

array([['1989', 'Americas', 'Guatemala', 'Beer', '0.62'],
       ['1989', 'Africa', 'Seychelles', 'Beer', '2.23'],
       ['1989', 'Americas', 'Costa Rica', 'Spirits', '4.51'],
       ...,
       ['1989', 'Eastern Mediterranean', 'Morocco', 'Spirits', '0.07'],
       ['1989', 'Europe', 'Poland', 'Beer', '2.03'],
       ['1989', 'Europe', 'Turkey', 'Other', '0']], dtype='<U75')

In [8]:
countries = world_alcohol[:, 2]
countries

array(['Viet Nam', 'Uruguay', "Cte d'Ivoire", ..., 'Switzerland',
       'Papua New Guinea', 'Swaziland'], dtype='<U75')

In [9]:
for country in countries:
    is_country = year[:, 2] == country
    country_consumption = year[is_country, :]
    alcohol_column = country_consumption[:, 4]
    is_empty = alcohol_column == ''
    alcohol_column[is_empty] = "0"
    alcohol_column = alcohol_column.astype(float)
    totals[country] = alcohol_column.sum()
    
print(totals)

{'Viet Nam': 0.16, 'Uruguay': 7.4399999999999995, "Cte d'Ivoire": 2.2, 'Colombia': 6.960000000000001, 'Saint Kitts and Nevis': 4.65, 'Guatemala': 2.47, 'Mauritius': 3.54, 'Angola': 2.28, 'Antigua and Barbuda': 4.69, 'Nigeria': 6.74, 'Botswana': 4.63, "Lao People's Democratic Republic": 5.95, 'Afghanistan': 0.0, 'Guinea-Bissau': 2.67, 'Costa Rica': 5.3999999999999995, 'Seychelles': 3.3000000000000003, 'Norway': 5.08, 'Kenya': 2.82, 'Myanmar': 0.16, 'Romania': 8.41, 'Turkey': 0.72, 'Comoros': 0.10999999999999999, 'Tunisia': 0.95, 'United Kingdom of Great Britain and Northern Ireland': 9.99, 'Bahrain': 4.89, 'Italy': 10.899999999999999, 'Sierra Leone': 4.380000000000001, 'Micronesia (Federated States of)': 0.0, 'Mauritania': 0.02, 'Russian Federation': 5.35, 'Egypt': 0.42000000000000004, 'Sweden': 7.47, 'Qatar': 1.4500000000000002, 'Burkina Faso': 3.99, 'Austria': 13.9, 'Czech Republic': 13.009999999999998, 'Ukraine': 5.32, 'China': 3.33, 'Lithuania': 0.0, 'Zimbabwe': 4.92, 'Trinidad and 

## Trouver le pays qui consomme le plus d'alcool

* Créer une variable highest_value qui gardera en mémoire la plus grande valeur du dictionnaire totals. On la fixe à 0 pour commencer.
* Créer une variable similaire qu'on nommera highest_key qui gardera en mémoire le nom du pays associé à la plus grande valeur. On la fixe à la valeur None.
* Parcourir chaque pays du dictionnaire totals :
    * Si la valeur associée au pays est plus grande que highest_value, assigner la valeur en question à la variable highest_value et assigner la clé correspondante (nom du pays) à la variable highest_key.
* Afficher lae pays qui consomme le plus d'alcool (variable highest_key)

In [14]:
totals

{'Viet Nam': 0.16,
 'Uruguay': 7.4399999999999995,
 "Cte d'Ivoire": 2.2,
 'Colombia': 6.960000000000001,
 'Saint Kitts and Nevis': 4.65,
 'Guatemala': 2.47,
 'Mauritius': 3.54,
 'Angola': 2.28,
 'Antigua and Barbuda': 4.69,
 'Nigeria': 6.74,
 'Botswana': 4.63,
 "Lao People's Democratic Republic": 5.95,
 'Afghanistan': 0.0,
 'Guinea-Bissau': 2.67,
 'Costa Rica': 5.3999999999999995,
 'Seychelles': 3.3000000000000003,
 'Norway': 5.08,
 'Kenya': 2.82,
 'Myanmar': 0.16,
 'Romania': 8.41,
 'Turkey': 0.72,
 'Comoros': 0.10999999999999999,
 'Tunisia': 0.95,
 'United Kingdom of Great Britain and Northern Ireland': 9.99,
 'Bahrain': 4.89,
 'Italy': 10.899999999999999,
 'Sierra Leone': 4.380000000000001,
 'Micronesia (Federated States of)': 0.0,
 'Mauritania': 0.02,
 'Russian Federation': 5.35,
 'Egypt': 0.42000000000000004,
 'Sweden': 7.47,
 'Qatar': 1.4500000000000002,
 'Burkina Faso': 3.99,
 'Austria': 13.9,
 'Czech Republic': 13.009999999999998,
 'Ukraine': 5.32,
 'China': 3.33,
 'Lithuania':

In [20]:
highest_value = 0
highest_key = None

for country in totals:
    consumption = totals[country]
    if highest_value < consumption:
        highest_value = consumption
        highest_key = country
        
print(highest_key)
print(highest_value)

Hungary
16.29
